version: '3'
services:
  cli:
   image: llslim/docker-phpcli:latest
   restart: always
   volumes:
     - ../work:/var/www/html
     - ./config/drush:/etc/drush
     - c:\users\kevin\.ssh:/home/dev/.ssh
     - C:\webroot\dev\archive:/var/www/archive

networks:
  default:
    external:
      name: lampserver_default
