version: '3'
services:
  cli:
   image: drupalcli:7t
   restart: always
   volumes:
     - C:\webroot\dev\html:/var/www/html
     - ./config/drush:/etc/drush
     - c:\users\kevin\.ssh:/var/www/src/.ssh
     - C:\webroot\dev\archive:/var/www/archive

networks:
  default:
    external:
      name: loaclhost_default
