version: '3'
services:
  cli:
   image: llslim/docker-phpcli:latest
   restart: always
   volumes:
     - ../html:/var/www/html
     - ./config/drush:/etc/drush
     - c:\users\kevin\.ssh:/var/www/src/.ssh
     - C:\webroot\dev\archive:/var/www/archive

networks:
  default:
    external:
      name: lampserver_default
