version: '3'
services:
  cli:
   image: llslim/docker-phpcli-drupal:latest
   restart: always
   volumes:
     - ../work:/var/www/html
     - ./config/drush:/etc/drush
     - ssh-vol:/home/dev/.ssh
     - ../archive/drush:/home/dev/.drush
     - ../archive:/var/www/archive

volumes:
  ssh-vol:
    external: true

networks:
  default:
    external:
      name: lampserver_default
