version: '3'
services:
  cli:
   image: llslim/docker-phpcli-drupal:latest
   restart: always
   volumes:
     - ../../workshop:/var/www/html
     - ssh-vol:/home/dev/.ssh
     - ../../conf/drush:/home/dev/.drush
     - ../../archive:/var/www/archive

volumes:
  ssh-vol:
    external: true

networks:
  default:
    external:
      name: lamp_default
